// This file is generated by Prismic local builder. Update with care!

export { default as Button } from './Button'
export { default as ImageSlice } from './ImageSlice'
export { default as QuoteSlice } from './QuoteSlice'
export { default as TextImageRight } from './TextImageRight'
export { default as VideoSlice } from './VideoSlice'
