// This file is generated by Prismic local builder. Update with care!

export { default as BannerSlice } from './BannerSlice'
export { default as CenterImageSlice } from './CenterImageSlice'
export { default as QuoteSlice } from './QuoteSlice'
export { default as SocialMediaSlice } from './SocialMediaSlice'
export { default as TextImageRight } from './TextImageRight'
export { default as ThreeGrideSlice } from './ThreeGrideSlice'
